export const LOCALIZATION_BULK_MAX_RESOURCES = 50;

export const LOCALIZATION_STATUS_FILTER_MAX_SCAN = 2000;

export const LOCALIZATION_LIST_DEFAULT_PAGE = 1;
export const LOCALIZATION_LIST_DEFAULT_LIMIT = 20;
export const LOCALIZATION_LIST_MAX_LIMIT = 50;

export const LOCALIZATION_REQUEST_THROTTLE_NAME = 'localization-request' as const;
export const LOCALIZATION_BULK_THROTTLE_NAME = 'localization-bulk' as const;
export const LOCALIZATION_RETRY_THROTTLE_NAME = 'localization-retry' as const;

export const LOCALIZATION_REQUEST_THROTTLE_LIMIT = 30;
export const LOCALIZATION_REQUEST_THROTTLE_TTL_MS = 60_000;
export const LOCALIZATION_BULK_THROTTLE_LIMIT = 10;
export const LOCALIZATION_BULK_THROTTLE_TTL_MS = 60_000;
export const LOCALIZATION_RETRY_THROTTLE_LIMIT = 20;
export const LOCALIZATION_RETRY_THROTTLE_TTL_MS = 60_000;
