export const FAMILY_PORTAL_CATECHIST_CLASSES_DEFAULT_PAGE = 1 as const;
export const FAMILY_PORTAL_CATECHIST_CLASSES_DEFAULT_LIMIT = 20 as const;
export const FAMILY_PORTAL_CATECHIST_CLASSES_MAX_LIMIT = 50 as const;
