import {
  AUTH_RBAC_SAMPLE_DOMAIN,
  AUTH_RBAC_SAMPLE_PASSWORD,
} from './auth-rbac.seed.constants';
import {
  CLASS_ENROLLMENT_DEMO_STUDENT_ALPHA_EMAIL,
  CLASS_ENROLLMENT_DEMO_STUDENT_BETA_NAME,
  CLASS_ENROLLMENT_SEED_ADMIN_EMAIL,
  CLASS_ENROLLMENT_SEED_CATECHIST_EMAIL,
  CLASS_ENROLLMENT_SEED_PARENT_EMAIL,
} from './class-enrollment.seed.constants';

/** Stable local demo password shared by Auth/RBAC sample users (dev/test only). */
export const GAMIFICATION_DEMO_SAMPLE_PASSWORD = AUTH_RBAC_SAMPLE_PASSWORD;

export const GAMIFICATION_DEMO_SUPER_ADMIN_EMAIL = `superadmin@${AUTH_RBAC_SAMPLE_DOMAIN}`;
export const GAMIFICATION_DEMO_PARISH_ADMIN_EMAIL = CLASS_ENROLLMENT_SEED_ADMIN_EMAIL;
export const GAMIFICATION_DEMO_CATECHIST_EMAIL = CLASS_ENROLLMENT_SEED_CATECHIST_EMAIL;
export const GAMIFICATION_DEMO_PARENT_EMAIL = CLASS_ENROLLMENT_SEED_PARENT_EMAIL;
export const GAMIFICATION_DEMO_STUDENT_ALPHA_EMAIL = CLASS_ENROLLMENT_DEMO_STUDENT_ALPHA_EMAIL;
export const GAMIFICATION_DEMO_STUDENT_BETA_NAME = CLASS_ENROLLMENT_DEMO_STUDENT_BETA_NAME;

export const GAMIFICATION_DEMO_REWARD_RULE_CODES = {
  lessonComplete10: 'LESSON_COMPLETE_10',
  practiceComplete5: 'PRACTICE_COMPLETE_5',
  attendancePresent5: 'ATTENDANCE_PRESENT_5',
  examComplete15: 'EXAM_COMPLETE_15',
} as const;

export const GAMIFICATION_DEMO_BADGE_CODES = {
  firstLesson: 'BADGE_FIRST_LESSON',
  practiceExplorer: 'BADGE_PRACTICE_EXPLORER',
} as const;

export const GAMIFICATION_DEMO_MILESTONE_CODES = {
  firstLesson: 'MILESTONE_FIRST_LESSON',
  firstMission: 'MILESTONE_FIRST_MISSION',
} as const;

export const GAMIFICATION_DEMO_MISSION_CODES = {
  complete3Lessons: 'MISSION_LESSONS_3',
  attend1Class: 'MISSION_ATTEND_1',
  scriptureDraft: 'MISSION_SCRIPTURE_DRAFT',
} as const;

export const GAMIFICATION_DEMO_DETERMINISTIC_EVENT_IDS = {
  lesson1: 'a1111111-1111-4111-8111-111111111111',
  practice1: 'a2222222-2222-4222-8222-222222222222',
  attendance1: 'a3333333-3333-4333-8333-333333333333',
} as const;

export const GAMIFICATION_DEMO_MANUAL_ADJUSTMENT = {
  delta: 20,
  reason: 'Demo: Active participation in community service and prayer',
} as const;
