export const CLASS_SESSION_TITLE_MAX_LENGTH = 128 as const;

export const ATTENDANCE_NOTE_MAX_LENGTH = 500 as const;

export const CLASS_SESSION_ROSTER_DISPLAY_NAME_MAX_LENGTH = 128 as const;

export const CLASS_OPERATIONS_ROSTER_FREEZE_PAGE_SIZE = 100 as const;
